services:
  web:
    container_name: web
    image: messenger.web
    ports:
      - "5000:8080"
    build:
      context: .
      dockerfile: src/Backend/Messenger.Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  identity.app:
    container_name: identity.app
    image: messenger.identity.app
    build:
      context: .
      dockerfile: src/Backend/Messenger.Identity.App/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
